# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/equilibrio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 600)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(30, 20, 256, 561))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Equilíbrio estático"))
        self.pushButton.setText(_translate("Dialog", "Voltar"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><a name=\"docs-internal-guid-306d3a3a-7fff-1129-edf5-db80940f1eea\"></a><span style=\" font-family:\'Arial\'; font-size:16pt; text-decoration: underline; color:#000000; background-color:transparent;\">E</span><span style=\" font-family:\'Arial\'; font-size:16pt; text-decoration: underline; color:#000000; background-color:transparent;\">quilíbrio estático</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#000000; background-color:transparent;\">     Para encontrar as forças de reação determinadas pelos apoios, usa-se, basicamente, a 1ª lei de Newton, a lei da inércia. Segundo esta, todos os corpos em equilíbrio ou em movimento retilíneo uniforme possuem força resultante sobre eles nula. O equilíbrio é a condição buscada neste caso. Então, soma-se as forças que agem sobre a peça, incluindo as forças de reação dos apoios, o resultado da soma, por sua vez, precisa ser igual a zero. Além do somatório das forças que atuam sobre o objeto ser igual a 0, a soma dos momentos que atuam sobre a estrutura também precisa ser igual a 0.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/formulas.png\" /><span style=\" font-size:8pt;\"><br /></span></p></body></html>"))
import resources_rc
