# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/exercicios.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 10, 331, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(30, 170, 731, 391))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 712, 736))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_2)
        self.formLayout.setObjectName("formLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser.setMinimumSize(QtCore.QSize(340, 170))
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textBrowser)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(340, 16777215))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textBrowser_2)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(340, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(340, 0))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(340, 16777215))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.textBrowser_3)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(340, 220))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBrowser_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setMinimumSize(QtCore.QSize(340, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setMinimumSize(QtCore.QSize(340, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setMinimumSize(QtCore.QSize(340, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(340, 220))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(340, 16777215))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.textBrowser_5)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(340, 170))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textBrowser_6)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setMinimumSize(QtCore.QSize(340, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButton_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(650, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.actionEx1 = QtWidgets.QAction(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Exercício 2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEx1.setIcon(icon)
        self.actionEx1.setObjectName("actionEx1")

        self.retranslateUi(Dialog)
        self.pushButton_7.clicked.connect(Dialog.close) # type: ignore
        self.pushButton.clicked.connect(Dialog.close) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.close) # type: ignore
        self.pushButton_3.clicked.connect(Dialog.close) # type: ignore
        self.pushButton_4.clicked.connect(Dialog.close) # type: ignore
        self.pushButton_5.clicked.connect(Dialog.close) # type: ignore
        self.pushButton_6.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Exercícios"))
        self.label.setText(_translate("Dialog", "Naoka\'s Solver"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/Exercício 2.jpg\" /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/Exercício 3.jpg\" /></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Exemplo 1"))
        self.pushButton_2.setText(_translate("Dialog", "Exemplo 2"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/Exercicío 8.jpg\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/Exercício 9.jpg\" /></p></body></html>"))
        self.pushButton_4.setText(_translate("Dialog", "Exemplo 4"))
        self.pushButton_3.setText(_translate("Dialog", "Exemplo 3"))
        self.pushButton_5.setText(_translate("Dialog", "Exemplo 5"))
        self.textBrowser_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/Exercício 10.jpg\" /></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/Exercício 11.jpg\" /></p></body></html>"))
        self.pushButton_6.setText(_translate("Dialog", "Exemplo 6"))
        self.pushButton_7.setText(_translate("Dialog", "Voltar"))
        self.actionEx1.setText(_translate("Dialog", "Ex1"))
import resources_rc
